language: java
addons:
  ssh_known_hosts: 5.196.65.205
  apt:
    packages:
    - sshpass
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ | tr "\n" ":")
cache:
  directories:
  - $HOME/.m2
before_install:
# Install coverage tool.
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar
script:
- mvn package
after_success:
# Upload test coverage.
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
# Update official "cerise" image.
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/cerise
# Run "cerise" image on reference server.
- RELEASE=`cat pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}'`
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker stop $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker rm -f $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "docker pull straumat/cerise:$RELEASE"
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "nohup docker run -l cerise -p 8080:8080 straumat/cerise:$RELEASE > /home/ci/cerise.logs &"
