language: java
addons:
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ | tr "\n" ":")
cache:
  directories:
  - $HOME/.m2
before_install:
  # Install coverage tool.
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar
script:
- mvn package
after_success:
  # Upload test coverage.
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml