language: java
addons:
  ssh_known_hosts: 5.196.65.205
  apt:
    packages:
    - sshpass
    - lftp
    - libssl-dev
  artifacts:
    paths:
    - $(git ls-files -o | grep -v lib | grep -v wrapper | grep -e jar$ | tr "\n" ":")
cache:
  directories:
  - $HOME/.m2
before_install:
# Install coverage tool.
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar
# Install swagger.
- wget -O ~/swagger-codegen-cli.jar http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar
# Install ftp.
- npm install ftp chalk
script:
- mvn package
after_success:
# Configuration.
- set cmd:default-protocol sftp
# Upload test coverage.
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
# Update official "cerise" image.
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/cerise
# Run "cerise" image on reference server.
- RELEASE=`cat pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}'`
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker stop $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker rm -f $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "docker pull straumat/cerise:$RELEASE"
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "nohup docker run -l cerise -p 80:8080 straumat/cerise:$RELEASE > /home/ci/cerise.logs &"
# Upload website.
- cd $TRAVIS_BUILD_DIR/website/
- lftp -e "mirror -R public /www/" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
# Upload documentation.
- cd $TRAVIS_BUILD_DIR/target/specifications/
- lftp -e "mirror -R specifications /www/specifications" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
# Generate clients.
- cd ~
- mkdir clients
- mkdir dist
- mkdir dist/$RELEASE
- wget http://api.cerise.tech/v2/api-docs
# Code generation.
- java -jar swagger-codegen-cli.jar generate -i api-docs -l android -o clients/android
- java -jar swagger-codegen-cli.jar generate -i api-docs -l csharp -o clients/csharp
- java -jar swagger-codegen-cli.jar generate -i api-docs -l cpprest -o clients/cpp
- java -jar swagger-codegen-cli.jar generate -i api-docs -l groovy -o clients/groovy
- java -jar swagger-codegen-cli.jar generate -i api-docs -l haskell -o clients/haskell
- java -jar swagger-codegen-cli.jar generate -i api-docs -l java -o clients/java
- java -jar swagger-codegen-cli.jar generate -i api-docs -l javascript -o clients/javascript
- java -jar swagger-codegen-cli.jar generate -i api-docs -l objc -o clients/objc
- java -jar swagger-codegen-cli.jar generate -i api-docs -l go -o clients/go
- java -jar swagger-codegen-cli.jar generate -i api-docs -l perl -o clients/perl
- java -jar swagger-codegen-cli.jar generate -i api-docs -l php -o clients/php
- java -jar swagger-codegen-cli.jar generate -i api-docs -l python -o clients/python
- java -jar swagger-codegen-cli.jar generate -i api-docs -l ruby -o clients/ruby
- java -jar swagger-codegen-cli.jar generate -i api-docs -l rust -o clients/rust
- java -jar swagger-codegen-cli.jar generate -i api-docs -l scala -o clients/scala
- java -jar swagger-codegen-cli.jar generate -i api-docs -l swift -o clients/swift
# Zipping files.
- cd ~/clients/android;zip -r cerise-client-android.zip *
- cd ~/clients/csharp;zip -r cerise-client-csharp.zip *
- cd ~/clients/cpp;zip -r cerise-client-cpp.zip *
- cd ~/clients/groovy;zip -r cerise-client-groovy.zip *
- cd ~/clients/haskell;zip -r cerise-client-haskell.zip *
- cd ~/clients/java;zip -r cerise-client-java.zip *
- cd ~/clients/cpp;zip -r cerise-client-cpp.zip *
- cd ~/clients/javascript;zip -r cerise-client-javascript.zip *
- cd ~/clients/objc;zip -r cerise-client-objc.zip *
- cd ~/clients/go;zip -r cerise-client-go.zip *
- cd ~/clients/perl;zip -r cerise-client-perl.zip *
- cd ~/clients/php;zip -r cerise-client-php.zip *
- cd ~/clients/python;zip -r cerise-client-python.zip *
- cd ~/clients/ruby;zip -r cerise-client-ruby.zip *
- cd ~/clients/rust;zip -r cerise-client-rust.zip *
- cd ~/clients/scala;zip -r cerise-client-scala.zip *
- cd ~/clients/swift;zip -r cerise-client-swift.zip *
# Moving them to dist and uploading.
- cd ~
- find ./clients/ -type f -name "*.zip" -exec cp {} dist/$RELEASE/ \;
- cd dist/
- lftp -e "mirror -R clients /www/clients" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST